### ISSUE TITLE
About the receiving data from arduino to android

### ISSUE THREAD

**Issue by JMJ15** [OmarAflak/Arduino-Library#12]
1st of all, thanks for your codes. I need to transfer and receive data between arduino and android. Send data from ardroid to arduino is okay but reverse is not working. 
@Override // arduino sent a message
    public void onArduinoMessage(byte[] bytes) {

        display(" Working! this function");
        display("> " +new String(bytes));
    }
This part is not working
rest all are fine.
I am very new to android. I am not getting idea to debug it. Seeking help

**Comment by OmarAflak** [comment]
Hi @JMJ15, thanks for reaching out.
How are you sending information from Arduino ? The library will display any text ending with "\n". Basically, you need to call `Serial.println("blabla")` from Arduino.
Let me know if it worked !

**Comment by JMJ15** [comment]
In readme  (for arduino side that Example code which sends back every character received) its given as Serial.print(). So i  try that, I try serial.write() but it not worked. Thanks for your help...When i try with serial.println() even with serial.write() it works..

**Comment by JMJ15** [comment]
One more doubt. When I try to add another vendor Id as arduino.addVendorId(XXXX); in android program, then product(Arduino 101 and Arduino Due) with that vendor ID did not get connected with android. I didn't get the message to accept the device in android program.

**Comment by OmarAflak** [comment]
Great! Right, I forgot to update the Readme.
Are you sure about the vendor id you're entering ? If it's an official Arduino the vendor id should be the one in the library.

**Comment by JMJ15** [comment]
yeah I am sure about the vendor id. Because i check it with board info in arduino and also through control panel via taking details of connected device.  It will be a 4 digit number right? Like 8087 or 2341(arduino uno)..Even if im checking the board info it shows like 0x2341 for arduino. Only need to take the last 4 digit?

**Comment by OmarAflak** [comment]
This issue was resolved in https://github.com/OmarAflak/Arduino-Library/issues/13.
