### ISSUE TITLE
For changing Vendor ID

### ISSUE THREAD

**Issue by JMJ15** [OmarAflak/Arduino-Library#13]
Hey,
I tried this code with arduino Uno (Vendor ID :0x2341) the code is working fine. But when I connect the product with Vendor ID: 1B4F and product ID: 9D0F for same purpose but it didn't worked with the code
arduino = new Arduino(this);
       //arduino.addVendorId(1B4F);
The product is a SAMD21 microprocessor with CDC USB profile. Is it not possible to do with this?

**Comment by vlaminck** [comment]
I have the same problem. I have an ESP32 which has a vendorId of `0x10c4`. Is there any way to connect to it using this library?

**Comment by JMJ15** [comment]
Is it working fine when u try with arduino.addVendorId(0x10C4) ?

**Comment by JMJ15** [comment]
Thanks a lot both of you. it works when I try with this code arduino.addVendorId(0x1B4F);
