### ISSUE TITLE
Cannot display message received normally 

### ISSUE THREAD

**Issue by Dartagnann** [OmarAflak/Arduino-Library#2]
Thank you very much for this library. But when I try to use my phone to read the value from DHT11 by my Arduino UNO, I met with this problem:
![qq 20180119125057](https://user-images.githubusercontent.com/30116916/35135329-81c1b5e0-fd17-11e7-9dd4-8acd26b8f65c.png)
Everything is fine on my pc:
![qq 20180119125630](https://user-images.githubusercontent.com/30116916/35135420-32a01f64-fd18-11e7-9052-f89a19e43584.png)

I am not very proficient in Android developing so could you please tell me that how can I fix this problem? Thank you again:)

**Comment by OmarAflak** [comment]
Hey ! I'm not sure.... but what baud rate are you using ? are you making a ` Serial.begin(9600)` in your Arduino code ?
