### ISSUE TITLE
Pending Mutability issue on android 12

### ISSUE THREAD

**Issue by musicmeetscode** [omaraflak/Arduino-Library#23]
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)

**Comment by omaraflak** [comment]
Fixed.
