### ISSUE TITLE
Changing Arduino vendor id 

### ISSUE THREAD

**Issue by fernando-s97** [OmarAflak/Arduino-Library#4]
Hi,

Is it possible to change the vendor id? My arduino has a different value of 9025.

Thank you.

**Comment by OmarAflak** [comment]
Hi,

What is the vendor id of your Arduino ?

Le 7 mars 2018 04:08, Fernando de Oliveira Santos <notifications@github.com> a écrit :

Hi,

Is it possible to change the vendor id? Mine one has a different value then 9025.

Thank you.

**Comment by fernando-s97** [comment]
0x0403

**Comment by OmarAflak** [comment]
I update the library, you should be able to use it now.

`implementation 'me.aflak.libraries:arduino:1.4.2'
`

**Comment by fernando-s97** [comment]
Thank you! I'll try the new version.

**Comment by skgadi** [comment]
Hi Omar,

I think it is useful to extend this library to support more than just the Arduino vendor IDs.

Is it possible to extend the support to all the vendor IDs?

I sometimes use Microchip USB micro-controllers and they use a different vendor ID.

Thank you.

**Comment by OmarAflak** [comment]
Hi @skgadi, it surely is possible.

The library is called Arduino, so it wouldn't be very consistent if I opened the lib the all vendor ids.

That said, you can clone the repo and make your own library. It's only one class, it's very easy.

**Comment by skgadi** [comment]
Thank you. I will do it :)

Also, I want to bring to your notice that with the new update of 1.4.2 my phone is not recognizing arduino uno board.

**Comment by OmarAflak** [comment]
@skgadi As you know from the other issue, I update the library to version **1.4.3**.
I added a `Log.i(TAG, vendorId)` in the library code, which means that if you take a look at your logcat when wiring your board you will see its vendor id printed.
Once you got it,  simply use `arduino.addVendorId(vendorId)` and it should be fine.

**Comment by skgadi** [comment]
@OmarAflak , Thank you for the update. It is working as expected.

Also, thank you for adding support for new vendor IDs.
