### ISSUE TITLE
Phone don't detect arduino

### ISSUE THREAD

**Issue by przemykomo** [OmarAflak/Arduino-Library#5]
Hi.
My phone just don't see arduino. There isn't anything like "Arduino attached!" and also no received messages.
Code - https://github.com/przemykomo/basic-communication
This isn't problem with arduino, when I use serial port on computer there are no problems.

**Comment by OmarAflak** [comment]
@przemykomo @skgadi  Sorry for the late response.
I fixed the library, you can now use the version **1.4.3** which works perfectly fine.
Moreover, if you have a device with a custom vendor id, you can use : 
```java
Arduino arduino = new Arduino(Context);
arduino.addVendorId(1234);
```

**Comment by skgadi** [comment]
Thank you very much. It is working as expected.
