### ISSUE TITLE
Installing the library - error

### ISSUE THREAD

**Issue by MarkFormigones** [OmarAflak/Arduino-Library#8]
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

My gradle Module

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.robotsystem"
        minSdkVersion 22
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

**Comment by OmarAflak** [comment]
Sorry, this is not an Arduino-Library related problem. Check this SO post :

https://stackoverflow.com/questions/46267621/unable-to-merge-dex
