### ISSUE TITLE
Determining VID at run time

### ISSUE THREAD

**Issue by pedroblanc** [OmarAflak/Arduino-Library#9]
It seems to me that the only way to use the library is to verify the Arduino VID beforehand using for example a computer or other app. I think we should be able to connect any Arduino and see 2 possible solutions to that.

1. Add a method that tells the library to listen to _any_ VID
Is this safe and possible?

2. Add a hook to notify for any device connected. This would allow, for example, the application to display a confirmation dialog describing the plugged device (vid, pid, name, ... ) and upon user confirmation tell the library to proceed with the connection attempt

Or is there already a way to accomplish this that I am missing?

I'm willing to work on the proposed solutions but would like some feedback on whether they are reasonable.

**Comment by OmarAflak** [comment]
Hi @pedroblanc. Usually the vendor id is unique (every authentic Arduino should have the same vid). As this library is meant to be used with Arduino I didn't feel the need to add others vids.
That said, you can check the library code, it's only one file, look at the code following this line :
```java
case UsbManager.ACTION_USB_DEVICE_ATTACHED
```
